apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-install
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: manifests/argocd-install
    # repoURL: https://github.com/kuadrant/deployment
    # targetRevision: HEAD
    repoURL: https://github.com/roivaz/kuadrant-deployment
    targetRevision: kuadrant-v1.0.0-rc4
  syncPolicy:
    automated:
      selfHeal: true
