apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kuadrant-install
  namespace: argocd
spec:
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
        - /spec/source/targetRevision
  goTemplate: true
  generators:
    - matrix:
        generators:
          - clusters: {}
          - git:
              # repoURL: https://github.com/kuadrant/deployment
              # revision: HEAD
              repoURL: https://github.com/roivaz/kuadrant-deployment
              revision: ha-setup
              files:
                - path: manifests/kuadrant/**/argocd-config.yaml
  template:
    metadata:
      name: "{{.path.basename}}.{{.nameNormalized}}"
    spec:
      project: default
      source:
        # repoURL: https://github.com/kuadrant/deployment
        # targetRevision: main
        repoURL: https://github.com/roivaz/kuadrant-deployment
        targetRevision: ha-setup
        path: "{{.path.path}}"
      destination:
        name: "{{.name}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
