apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kuadrant-install
spec:
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
        - /spec/source/targetRevision
  goTemplate: true
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: argocd.argoproj.io/secret-type
                    operator: Exists
          - git:
              # repoURL: https://github.com/kuadrant/deployment
              # revision: HEAD
              repoURL: https://github.com/roivaz/kuadrant-deployment
              revision: kuadrant-v1.0.0-rc4
              files:
                - path: manifests/kuadrant/**/argocd-config.yaml
  template:
    metadata:
      name: "{{.path.basename}}.{{.nameNormalized}}"
    spec:
      project: default
      source:
        # repoURL: https://github.com/kuadrant/deployment
        # targetRevision: main
        repoURL: https://github.com/roivaz/kuadrant-deployment
        targetRevision: kuadrant-v1.0.0-rc4
        path: '{{.path.path}}/overlays/{{or (index .metadata.labels "vendor") "k8s" | lower}}'
      destination:
        name: "{{.name}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
