---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-worker
  namespace: argocd
spec:
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
        - /spec/source/targetRevision
  goTemplate: true
  generators:
    - clusters:
        selector:
          matchExpressions:
            # A cluster secret is not automatically created for the local cluster, so we need to
            # add one (or edit the in-cluster cluste rthrough the argocd UI) for it. Only after
            # evaluating that the secret exists it is safe to evaluate the other installation conditions
            - key: argocd.argoproj.io/secret-type
              operator: Exists
            # Only install argocd through the repo yamls if the cluster secret has been marked with the
            # following label. This allows users to make use of the resources in this repo while managing
            # their own installation of argocd
            - key: vendor
              operator: NotIn
              values:
                - "OpenShift"
  template:
    metadata:
      name: "observability-worker.{{.nameNormalized}}"
    spec:
      destination:
        namespace: monitoring
        name: "{{.name}}"
      project: default
      source:
        path: manifests/observability-worker/k8s
        # repoURL: https://github.com/kuadrant/deployment
        # targetRevision: HEAD
        repoURL: https://github.com/roivaz/kuadrant-deployment
        targetRevision: ha-setup
        kustomize:
          patches:
            - target:
                group: monitoring.coreos.com
                version: v1
                kind: Prometheus
                name: k8s
              patch: |-
                - op: replace
                  path: /spec/remoteWrite/0/writeRelabelConfigs/0/replacement
                  value: "{{ .name }}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - ServerSideApply=true
