---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kuadrant-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kuadrant-operator
  source: operatorhubio-catalog
  sourceNamespace: olm

---
kind: OperatorGroup
apiVersion: operators.coreos.com/v1
metadata:
  name: kuadrant
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  upgradeStrategy: Default
