apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: limitador-redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: limitador-redis
  replicas: 1
  serviceName: limitador-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: limitador-redis
    spec:
      containers:
        - name: redis
          image: redis:6.0.5-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
          livenessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: 6379
          readinessProbe:
            initialDelaySeconds: 15
            tcpSocket:
              port: 6379
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
          ## container > limitador-redis > volumeMounts
          volumeMounts:
            - name: limitador-redis-storage
              mountPath: /data
              subPath: data
  volumeClaimTemplates:
    - metadata:
        name: limitador-redis-storage
      spec:
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi

---
apiVersion: v1
kind: Service
metadata:
  name: limitador-redis
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: redis
  selector:
    app.kubernetes.io/name: limitador-redis
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-config
stringData:
  URL: redis://limitador-redis:6379